version: '3.8'
services:
  graphdb:
    image: ontotext/graphdb:10.7.1
    restart: unless-stopped
    ports:
      - "7200:7200"
    environment:
      GDB_JAVA_OPTS: -Xms4G -Xmx4G
      graphdb.connector.port: "7200"
      graphdb.gpt.token: ""
      graphdb.gpt.model: gpt-3.5-turbo
      graphdb.gpt.timeout: 180
      graphdb.gpt.url: https://api.openai.com/v1/chat/completions
    volumes:
      - graphdb_data:/opt/graphdb/home

volumes:
    graphdb_data:

